# SonarQube Cloud Configuration
sonar.projectKey=SonarSource_sonarqube-cli
sonar.organization=sonarsource
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=tests/coverage/reports/unit/lcov.info,tests/coverage/reports/integration/lcov.info
