# SonarQube Cloud Configuration
sonar.projectKey=SonarSource_sonarqube-cli
sonar.organization=sonarsource
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=tests/coverage/reports/unit/lcov.info,tests/coverage/reports/integration/lcov.info

# S104 (file too many lines) is not useful for test files
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S104
sonar.issue.ignore.multicriteria.e1.resourceKey=tests/**
