/*
 * SonarQube CLI
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

/**
 * UX Report — curated CLI scenarios for UX documentation.
 *
 * Each uxDescribe() block is a report section; each uxIt() is a scenario.
 * After all tests complete, outputs are written to ux-report/cli-output-report.md.
 *
 * Run:
 *   bun run pretest:integration                          # build binary + resources (once)
 *   bun test ./build-scripts/ux-report/generate-ux-report.ts   # generate the report
 *
 * To add a scenario: add a uxIt() inside the appropriate uxDescribe() block,
 * or add a new uxDescribe() block at the bottom.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { afterAll, afterEach, beforeEach, describe, it } from 'bun:test';

import { TestHarness } from '../../tests/integration/harness';
import type { CliResult } from '../../tests/integration/harness/types.ts';
import { commitFile, initGitRepo } from '../../tests/integration/specs/hook/git-test-helpers.ts';

const OUTPUT_PATH = join(import.meta.dir, '../../ux-report/cli-output-report.md');
const DEFAULT_TIMEOUT = 30000;

const TOKEN = 'test-token-12345';
const ORG = 'my-org';
const PROJECT = 'my-project';
const ORG_UUID = 'org-uuid-v4';

// ── Report infrastructure ──────────────────────────────────────────────────

interface CapturedRun {
  group: string;
  label: string;
  stdout: string;
  stderr: string;
  exitCode: number;
}

const captured: CapturedRun[] = [];
let currentGroup = '';

const ANSI_RE = /\x1B\[[0-9;?]*[A-Za-z]|\x1B\].*?\x07/g;

function stripAnsi(s: string): string {
  return s.replace(ANSI_RE, '');
}

/**
 * Wraps describe() and tracks the current section name so uxIt() can capture it
 * at registration time (describe() calls fn() synchronously during module load).
 */
function uxDescribe(name: string, fn: () => void): void {
  describe(name, () => {
    currentGroup = name; // set inside the callback so it runs when describe executes, not at module load
    fn();
  });
}

/**
 * Wraps it(): runs fn(), captures the CliResult, and records it for the report.
 * The it() label is used directly as the report entry heading.
 */
function uxIt(label: string, fn: () => Promise<CliResult>, options?: { timeout?: number }): void {
  const group = currentGroup; // closed over at registration time — always correct
  it(
    label,
    async () => {
      const result = await fn();
      captured.push({
        group,
        label,
        stdout: stripAnsi(result.stdout).trim(),
        stderr: stripAnsi(result.stderr).trim(),
        exitCode: result.exitCode,
      });
    },
    { timeout: options?.timeout ?? DEFAULT_TIMEOUT },
  );
}

/**
 * Convenience wrapper for scenarios that need a unique harness per test
 * (e.g. error paths where each test needs a differently-configured server).
 */
async function withHarness(fn: (h: TestHarness) => Promise<CliResult>): Promise<CliResult> {
  const h = await TestHarness.create();
  try {
    return await fn(h);
  } finally {
    await h.dispose();
  }
}

afterAll(() => {
  if (captured.length === 0) return;

  // Reconstruct sections in insertion order
  const sectionOrder: string[] = [];
  const sections = new Map<string, CapturedRun[]>();
  for (const run of captured) {
    if (!sections.has(run.group)) {
      sectionOrder.push(run.group);
      sections.set(run.group, []);
    }
    sections.get(run.group)!.push(run);
  }

  const lines: string[] = [
    '# CLI Output Report',
    '',
    `> **Generated:** ${new Date().toISOString()}  `,
    `> **Total runs captured:** ${captured.length}`,
    '',
    'Captures the actual output for curated CLI scenarios organized by state context.',
    '',
    '> **Do not edit this file manually.** Regenerate with:',
    '> ```',
    '> bun run pretest:integration',
    '> bun test ./build-scripts/docs/generate-ux-report.ts',
    '> ```',
    '',
    '---',
    '',
    '## Table of Contents',
    '',
    ...sectionOrder.map(
      (name, i) =>
        `- [${i + 1}. ${name}](#${i + 1}-${name
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-|-$/g, '')})`,
    ),
    '',
    '---',
    '',
  ];

  let sectionIndex = 1;
  for (const name of sectionOrder) {
    lines.push(`## ${sectionIndex++}. ${name}`);
    lines.push('');
    for (const run of sections.get(name)!) {
      lines.push(`#### ${run.label}`);
      lines.push('');
      lines.push(`**Exit code:** ${run.exitCode}`);
      lines.push('');
      const output = [run.stdout, run.stderr].filter(Boolean).join('\n');
      if (output) {
        lines.push('**Output:**');
        lines.push('```');
        lines.push(output);
        lines.push('```');
      } else {
        lines.push('*(no output)*');
      }
      lines.push('');
      lines.push('---');
      lines.push('');
    }
  }

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf-8');
  console.log(`\n  UX report → ${OUTPUT_PATH} (${captured.length} scenarios)`);
});

// ── Helpers ────────────────────────────────────────────────────────────────

function cloudEnvFor(serverUrl: string): Record<string, string> {
  return {
    SONARQUBE_CLI_SONARCLOUD_URL: serverUrl,
    SONARQUBE_CLI_SONARCLOUD_API_URL: serverUrl,
  };
}

// ══ Scenarios ══════════════════════════════════════════════════════════════

// ── 1. Help, Version, and Structural Commands ──────────────────────────────

uxDescribe('Help, Version, and Structural Commands', () => {
  let harness: TestHarness;
  beforeEach(async () => {
    harness = await TestHarness.create();
  });
  afterEach(async () => {
    await harness.dispose();
  });

  uxIt('no arguments (shows help)', () => harness.run(''));
  uxIt('--version', () => harness.run('--version'));
  uxIt('auth --help', () => harness.run('auth --help'));
  uxIt('analyze --help', () => harness.run('analyze --help'));
  uxIt('integrate --help', () => harness.run('integrate --help'));
  uxIt('list --help', () => harness.run('list --help'));
  uxIt('config telemetry — show current value', () => harness.run('config telemetry'));
});

// ── 2. Unauthenticated State ───────────────────────────────────────────────

uxDescribe('Unauthenticated State', () => {
  let harness: TestHarness;
  beforeEach(async () => {
    harness = await TestHarness.create();
  });
  afterEach(async () => {
    await harness.dispose();
  });

  uxIt('auth status — no saved connection', () => harness.run('auth status'));
  uxIt('auth logout — not logged in', () => harness.run('auth logout'));
  uxIt('auth purge — no keychain tokens', () => harness.run('auth purge'));
  uxIt('config telemetry --enabled', () => harness.run('config telemetry --enabled'));
  uxIt('config telemetry --disabled', () => harness.run('config telemetry --disabled'));
  uxIt('api GET — not authenticated', () => harness.run('api GET /api/system/status'));
  uxIt('list projects — not authenticated', () => harness.run('list projects'));
  uxIt(`list issues — not authenticated`, () => harness.run(`list issues -p ${PROJECT}`));
  uxIt('remediate — not authenticated', () => harness.run('remediate'));
  uxIt('analyze agentic — not authenticated', async () => {
    harness.cwd.writeFile('src/index.ts', 'const x = 1;');
    return harness.run('analyze agentic --file src/index.ts');
  });
  uxIt('analyze agentic — no Cloud/project configured', () => harness.run('analyze agentic'));
});

// ── 3. Option Validation Errors ────────────────────────────────────────────

uxDescribe('Option Validation Errors', () => {
  let harness: TestHarness;
  beforeEach(async () => {
    harness = await TestHarness.create();
  });
  afterEach(async () => {
    await harness.dispose();
  });

  uxIt('api: invalid HTTP method', () => harness.run('api TRACE /path'));
  uxIt('api: endpoint missing leading /', () => harness.run('api GET path'));
  uxIt('api: --data not valid for GET', () => harness.run("api GET /path --data '{}'"));
  uxIt('api: --data must be valid JSON', () => harness.run("api POST /path --data 'not-json'"));
  uxIt('list issues: --project is required', () => harness.run('list issues'));
  uxIt('list issues: --page-size below minimum (0)', () =>
    harness.run('list issues -p k --page-size 0'),
  );
  uxIt('list issues: --page-size above maximum (501)', () =>
    harness.run('list issues -p k --page-size 501'),
  );
  uxIt('list issues: invalid --severities value', () =>
    harness.run('list issues -p k --severities EXTREME'),
  );
  uxIt('list issues: invalid --statuses value', () =>
    harness.run('list issues -p k --statuses CLOSED'),
  );
  uxIt('list issues: invalid --format value', () => harness.run('list issues -p k --format xml'));
  uxIt('list projects: --page-size below minimum (0)', () =>
    harness.run('list projects --page-size 0'),
  );
  uxIt('analyze agentic: --staged and --base are mutually exclusive', () =>
    harness.run('analyze agentic --staged --base main'),
  );
  uxIt('analyze agentic: --file not found', () =>
    harness.run('analyze agentic --file nonexistent.ts'),
  );
  uxIt('analyze secrets: no paths and no --stdin', () => harness.run('analyze secrets'));
  uxIt('config telemetry: --enabled and --disabled conflict', () =>
    harness.run('config telemetry --enabled --disabled'),
  );
  uxIt('auth login: --with-token without --server', () =>
    harness.run('auth login --with-token tok'),
  );
  uxIt('auth login: invalid server URL', () => harness.run('auth login --server not-a-url'));
});

// ── 4. SonarQube Server (On-Premise) — Happy Path ─────────────────────────

uxDescribe('SonarQube Server (On-Premise) — Happy Path', () => {
  let harness: TestHarness;
  let serverUrl: string;

  beforeEach(async () => {
    harness = await TestHarness.create();
    const server = await harness
      .newFakeServer()
      .withAuthToken(TOKEN)
      .withProject(PROJECT, (p) => {
        p.withIssue({
          key: 'ISSUE-1',
          ruleKey: 'java:S100',
          message: 'Method name does not match regex',
          severity: 'MAJOR',
        });
        p.withIssue({
          key: 'ISSUE-2',
          ruleKey: 'java:S2259',
          message: 'Possible NullPointerException',
          severity: 'BLOCKER',
        });
        p.withIssue({
          key: 'ISSUE-3',
          ruleKey: 'ts:S1848',
          message: 'Object created to be immediately dropped',
          severity: 'MAJOR',
          status: 'CONFIRMED',
        });
      })
      .start();
    serverUrl = server.baseUrl();
    harness.state().withAuth(serverUrl, TOKEN);
  });
  afterEach(async () => {
    await harness.dispose();
  });

  uxIt('auth login --with-token', () =>
    harness.run(`auth login --with-token ${TOKEN} --server ${serverUrl}`),
  );
  uxIt('auth status (connected)', () => harness.run('auth status'));
  uxIt('api GET /api/authentication/validate', () =>
    harness.run('api GET /api/authentication/validate'),
  );
  uxIt('api GET /api/system/status', () => harness.run('api GET /api/system/status'));
  uxIt('list projects', () => harness.run('list projects'));
  uxIt('list issues (JSON output)', () => harness.run(`list issues -p ${PROJECT}`));
  uxIt('list issues --format table', () => harness.run(`list issues -p ${PROJECT} --format table`));
  uxIt('list issues --format csv', () => harness.run(`list issues -p ${PROJECT} --format csv`));
  uxIt('list issues --format toon', () => harness.run(`list issues -p ${PROJECT} --format toon`));
  uxIt('list issues --severities BLOCKER', () =>
    harness.run(`list issues -p ${PROJECT} --severities BLOCKER`),
  );
  uxIt('analyze agentic (on-premise = skipped, exit 0)', async () => {
    harness.cwd.writeFile('src/index.ts', 'const x = 1;');
    return harness.run('analyze agentic --file src/index.ts');
  });
  uxIt('remediate (on-premise = Cloud required)', () =>
    harness.run(`remediate -p ${PROJECT} --issues ISSUE-1`),
  );
  uxIt('auth logout', () => harness.run('auth logout'));
});

// ── 5. SonarQube Server — Auth Error Paths ────────────────────────────────

uxDescribe('SonarQube Server — Auth Error Paths', () => {
  uxIt('auth status — token missing from keychain', () =>
    withHarness(async (h) => {
      const server = await h.newFakeServer().withAuthToken(TOKEN).start();
      h.state().withActiveConnection(server.baseUrl(), 'on-premise');
      return h.run('auth status');
    }),
  );

  uxIt('auth status — token invalid (401)', () =>
    withHarness(async (h) => {
      const server = await h.newFakeServer().withAuthToken('correct-token').start();
      h.state().withAuth(server.baseUrl(), 'wrong-token');
      return h.run('auth status');
    }),
  );

  uxIt('auth status — server unreachable', () =>
    withHarness(async (h) => {
      h.state().withAuth('http://127.0.0.1:1', 'any-token');
      return h.run('auth status');
    }),
  );

  uxIt('auth logout — token revocation fails, local cleanup proceeds', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withTokenRevocationFailure(500)
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN).withTokenName('browser-generated-token-name');
      return h.run('auth logout');
    }),
  );

  uxIt('auth logout — tokenName known but no keychain token (hint to revoke manually)', () =>
    withHarness(async (h) => {
      const server = await h.newFakeServer().withAuthToken(TOKEN).start();
      h.state()
        .withActiveConnection(server.baseUrl(), 'on-premise')
        .withTokenName('browser-generated-token-name');
      return h.run('auth logout');
    }),
  );
});

// ── 6. SonarQube Cloud — Happy Path ───────────────────────────────────────

uxDescribe('SonarQube Cloud — Happy Path', () => {
  let harness: TestHarness;
  let cloudUrl: string;

  beforeEach(async () => {
    harness = await TestHarness.create();
    const server = await harness
      .newFakeServer()
      .withAuthToken(TOKEN)
      .withOrganizations([{ key: ORG, name: 'My Organization' }])
      .withProject(PROJECT, (p) => {
        p.withIssue({
          key: 'ISSUE-1',
          ruleKey: 'java:S100',
          message: 'Method name does not match regex',
          severity: 'MAJOR',
          fixableByAgent: true,
        });
        p.withIssue({
          key: 'ISSUE-2',
          ruleKey: 'security:S3649',
          message: 'Possible SQL injection',
          severity: 'BLOCKER',
        });
      })
      .withSqaaEntitlement(ORG, ORG_UUID, { eligible: true, enabled: true })
      .withSqaaResponse({
        issues: [{ rule: 'java:S100', message: 'Method name does not match regex', startLine: 3 }],
      })
      .withOrgEntitlement(true, true)
      .start();
    cloudUrl = server.baseUrl();
    harness
      .state()
      .withAuth(cloudUrl, TOKEN, ORG)
      .withSqaaExtension(harness.cwd.path, PROJECT, ORG, cloudUrl);
  });
  afterEach(async () => {
    await harness.dispose();
  });

  uxIt('auth login (Cloud, with org)', () =>
    harness.run(`auth login --with-token ${TOKEN} --server ${cloudUrl} --org ${ORG}`, {
      extraEnv: cloudEnvFor(cloudUrl),
    }),
  );
  uxIt('auth status (Cloud, connected)', () => harness.run('auth status'));
  uxIt('api GET /api/authentication/validate', () =>
    harness.run('api GET /api/authentication/validate'),
  );
  uxIt('list projects', () => harness.run('list projects'));
  uxIt('list issues (JSON output)', () => harness.run(`list issues -p ${PROJECT}`));
  uxIt('list issues --format table', () => harness.run(`list issues -p ${PROJECT} --format table`));
  uxIt('list issues --format csv', () => harness.run(`list issues -p ${PROJECT} --format csv`));
  uxIt('list issues --format toon', () => harness.run(`list issues -p ${PROJECT} --format toon`));
  uxIt('list issues --severities BLOCKER', () =>
    harness.run(`list issues -p ${PROJECT} --severities BLOCKER`),
  );
  uxIt('analyze agentic --file (issue found, exit 51)', async () => {
    harness.cwd.writeFile('src/Calculator.ts', 'function calculateResult() { return null; }');
    return harness.run('analyze agentic --file src/Calculator.ts');
  });
  uxIt('analyze agentic --staged (no staged files → empty changeset)', async () => {
    initGitRepo(harness.cwd.path);
    commitFile(harness.cwd.path, '.gitignore', '');
    return harness.run('analyze agentic --staged');
  });
  uxIt('remediate -p my-project --issues ISSUE-1', () =>
    harness.run(`remediate -p ${PROJECT} --issues ISSUE-1`),
  );
  uxIt('remediate (non-TTY, --issues required)', () => harness.run(`remediate -p ${PROJECT}`));
  uxIt('list issues — project with no issues (empty result)', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Org' }])
        .withProject(PROJECT)
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      return h.run(`list issues -p ${PROJECT}`);
    }),
  );
  uxIt('remediate — no eligible issues found (exit 0)', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Org' }])
        .withProject(PROJECT, (p) => {
          p.withIssue({ ruleKey: 'java:S100', message: 'Not fixable', fixableByAgent: false });
        })
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      return h.run(`remediate -p ${PROJECT}`, { extraEnv: { SONARQUBE_CLI_MOCK_TTY: '1' } });
    }),
  );
  uxIt('remediate — interactive: select issue and confirm (exit 0)', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Org' }])
        .withProject(PROJECT, (p) => {
          p.withIssue({
            key: 'ISSUE-1',
            ruleKey: 'java:S100',
            message: 'Fixable issue',
            severity: 'MAJOR',
            fixableByAgent: true,
          });
        })
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      return h.run(`remediate -p ${PROJECT}`, {
        extraEnv: { SONARQUBE_CLI_MOCK_TTY: '1' },
        stdinChunks: [' ', '\r'],
      });
    }),
  );
  uxIt('auth logout (Cloud)', () => harness.run('auth logout'));
});

// ── 7. SonarQube Cloud — Error Paths ──────────────────────────────────────

uxDescribe('SonarQube Cloud — Error Paths', () => {
  uxIt('remediate — org not eligible', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Org' }])
        .withOrgEntitlement(false, false)
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      return h.run(`remediate -p ${PROJECT} --issues ISSUE-1`);
    }),
  );

  uxIt('remediate — eligible but not enabled', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Org' }])
        .withOrgEntitlement(true, false)
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      return h.run(`remediate -p ${PROJECT} --issues ISSUE-1`);
    }),
  );

  uxIt('remediate — entitlement check fails (5xx, could not verify)', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Org' }])
        .withProject(PROJECT, (p) => {
          p.withIssue({ ruleKey: 'java:S100', message: 'Fixable issue', fixableByAgent: true });
        })
        .withOrgsLookupError(503)
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      return h.run(`remediate -p ${PROJECT}`, { extraEnv: { SONARQUBE_CLI_MOCK_TTY: '1' } });
    }),
  );

  uxIt('remediate --issues — too many keys (21 keys, exit 2)', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Org' }])
        .withProject(PROJECT)
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      const tooMany = Array.from({ length: 21 }, (_, i) => `k${i + 1}`).join(',');
      return h.run(`remediate -p ${PROJECT} --issues ${tooMany}`);
    }),
  );

  uxIt('analyze dependency-risks — SCA disabled', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Org' }])
        .withScaEnabled(false)
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      return h.run(`analyze dependency-risks -p ${PROJECT}`);
    }),
  );

  uxIt('analyze dependency-risks — project not found', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Org' }])
        .withScaEnabled(true)
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      return h.run('analyze dependency-risks -p nonexistent-project');
    }),
  );

  uxIt(
    'analyze dependency-risks — auto-installs sca-scanner-cli (install step + scanner fails)',
    () =>
      withHarness(async (h) => {
        await h.newFakeBinariesServer().start();
        const server = await h
          .newFakeServer()
          .withAuthToken(TOKEN)
          .withOrganizations([{ key: ORG, name: 'My Org' }])
          .withScaEnabled(true)
          .withProject(PROJECT)
          .withProjectSettings(PROJECT, [])
          .start();
        h.state().withAuth(server.baseUrl(), TOKEN, ORG);
        return h.run(`analyze dependency-risks -p ${PROJECT}`);
      }),
    { timeout: 60000 },
  );

  uxIt('analyze agentic — no project configured (skipped, exit 0)', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withSqaaResponse({ issues: [] })
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      h.cwd.writeFile('src/index.ts', 'const x = 1;');
      return h.run('analyze agentic --file src/index.ts');
    }),
  );

  uxIt('analyze agentic — API-level error from server', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withSqaaResponse({
          issues: [],
          errors: [
            {
              code: 'NOT_ENTITLED',
              message: 'Organization is not entitled to Agentic Analysis',
            },
          ],
        })
        .start();
      h.state()
        .withAuth(server.baseUrl(), TOKEN, ORG)
        .withSqaaExtension(h.cwd.path, PROJECT, ORG, server.baseUrl());
      h.cwd.writeFile('src/index.ts', 'const x = 1;');
      return h.run('analyze agentic --file src/index.ts');
    }),
  );

  uxIt('analyze agentic — SQAA API rate limited (429)', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withSqaaStatusCode(429, 'Too Many Requests')
        .start();
      h.state()
        .withAuth(server.baseUrl(), TOKEN, ORG)
        .withSqaaExtension(h.cwd.path, PROJECT, ORG, server.baseUrl());
      h.cwd.writeFile('src/index.ts', 'const x = 1;');
      return h.run('analyze agentic --file src/index.ts');
    }),
  );
});

// ── 8. Integrate Commands ──────────────────────────────────────────────────

uxDescribe('Integrate Commands', () => {
  uxIt('integrate claude -p my-project --non-interactive (Cloud)', () =>
    withHarness(async (h) => {
      await h.newFakeBinariesServer().start();
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Org' }])
        .withProject(PROJECT)
        .start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      h.cwd.writeFile(
        'sonar-project.properties',
        `sonar.host.url=${server.baseUrl()}\nsonar.projectKey=${PROJECT}\n`,
      );
      return h.run(`integrate claude -p ${PROJECT} --non-interactive`);
    }),
  );

  uxIt('integrate claude --non-interactive (on-premise server)', () =>
    withHarness(async (h) => {
      await h.newFakeBinariesServer().start();
      const server = await h.newFakeServer().withAuthToken(TOKEN).withProject(PROJECT).start();
      h.state().withAuth(server.baseUrl(), TOKEN);
      h.cwd.writeFile(
        'sonar-project.properties',
        `sonar.host.url=${server.baseUrl()}\nsonar.projectKey=${PROJECT}\n`,
      );
      return h.run('integrate claude --non-interactive');
    }),
  );

  uxIt('integrate git --hook pre-commit --non-interactive', () =>
    withHarness(async (h) => {
      await h.newFakeBinariesServer().start();
      const server = await h.newFakeServer().withAuthToken(TOKEN).withProject(PROJECT).start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      h.cwd.writeFile(
        'sonar-project.properties',
        `sonar.host.url=${server.baseUrl()}\nsonar.projectKey=${PROJECT}\n`,
      );
      initGitRepo(h.cwd.path);
      return h.run('integrate git --hook pre-commit --non-interactive');
    }),
  );

  uxIt('integrate git --hook pre-push --non-interactive', () =>
    withHarness(async (h) => {
      await h.newFakeBinariesServer().start();
      const server = await h.newFakeServer().withAuthToken(TOKEN).withProject(PROJECT).start();
      h.state().withAuth(server.baseUrl(), TOKEN, ORG);
      h.cwd.writeFile(
        'sonar-project.properties',
        `sonar.host.url=${server.baseUrl()}\nsonar.projectKey=${PROJECT}\n`,
      );
      initGitRepo(h.cwd.path);
      return h.run('integrate git --hook pre-push --non-interactive');
    }),
  );

  uxIt('integrate copilot (project-level)', () =>
    withHarness(async (h) => {
      const server = await h.newFakeServer().withAuthToken(TOKEN).start();
      h.state().withAuth(server.baseUrl(), TOKEN).withSecretsBinaryInstalled();
      return h.run('integrate copilot');
    }),
  );

  uxIt('integrate copilot --global', () =>
    withHarness(async (h) => {
      const server = await h.newFakeServer().withAuthToken(TOKEN).start();
      h.state().withAuth(server.baseUrl(), TOKEN).withSecretsBinaryInstalled();
      return h.run('integrate copilot --global');
    }),
  );
});

// ── 9. Analyze Secrets ────────────────────────────────────────────────────

uxDescribe('Analyze Secrets', () => {
  uxIt('binary not installed (auto-installs from download server)', () =>
    withHarness(async (h) => {
      const server = await h.newFakeServer().withAuthToken(TOKEN).start();
      h.state().withAuth(server.baseUrl(), TOKEN);
      h.cwd.writeFile('test.ts', 'const x = 1;');
      return h.run('analyze secrets test.ts');
    }),
  );

  uxIt('no secrets found (exit 0)', () =>
    withHarness(async (h) => {
      const server = await h.newFakeServer().withAuthToken(TOKEN).start();
      h.state().withAuth(server.baseUrl(), TOKEN).withSecretsBinaryInstalled();
      h.cwd.writeFile('clean.ts', 'const greeting = "hello world";');
      return h.run('analyze secrets clean.ts');
    }),
  );
});

// ── 10. Interactive auth login ─────────────────────────────────────────────

uxDescribe('Interactive auth login', () => {
  uxIt('browser OAuth — on-premise server', () =>
    withHarness(async (h) => {
      const server = await h.newFakeServer().withAuthToken(TOKEN).start();
      return h.run(`auth login --server ${server.baseUrl()}`, {
        browserToken: TOKEN,
        browserTokenName: 'cli-generated-token-name',
      });
    }),
  );

  uxIt('browser OAuth — Cloud, single org auto-selected', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Organization' }])
        .start();
      const cloudUrl = server.baseUrl();
      return h.run(`auth login --server ${cloudUrl}`, {
        extraEnv: cloudEnvFor(cloudUrl),
        browserToken: TOKEN,
      });
    }),
  );

  uxIt('browser OAuth — Cloud, select org from list (↓ Enter → org 2)', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([
          { key: 'my-org', name: 'My Org' },
          { key: 'my-org-2', name: 'My Org 2' },
        ])
        .start();
      const cloudUrl = server.baseUrl();
      return h.run(`auth login --server ${cloudUrl}`, {
        extraEnv: cloudEnvFor(cloudUrl),
        browserToken: TOKEN,
        stdin: '\x1b[B\r',
      });
    }),
  );

  uxIt('browser OAuth — Cloud, >10 orgs (truncation notice)', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations(
          Array.from({ length: 10 }, (_, i) => ({ key: `org-${i}`, name: `Org ${i}` })),
        )
        .withOrganizationTotal(200)
        .start();
      const cloudUrl = server.baseUrl();
      return h.run(`auth login --server ${cloudUrl}`, {
        extraEnv: cloudEnvFor(cloudUrl),
        browserToken: TOKEN,
        stdin: '\r',
      });
    }),
  );

  uxIt('browser OAuth — Cloud, no org memberships → manual key entry', () =>
    withHarness(async (h) => {
      const server = await h.newFakeServer().withAuthToken(TOKEN).start();
      const cloudUrl = server.baseUrl();
      return h.run(`auth login --server ${cloudUrl}`, {
        extraEnv: cloudEnvFor(cloudUrl),
        browserToken: TOKEN,
        stdin: 'open-source-org\r',
      });
    }),
  );

  uxIt('browser OAuth — Cloud, org selection cancelled (Ctrl+C)', () =>
    withHarness(async (h) => {
      const server = await h.newFakeServer().withAuthToken(TOKEN).start();
      const cloudUrl = server.baseUrl();
      return h.run(`auth login --server ${cloudUrl}`, {
        extraEnv: cloudEnvFor(cloudUrl),
        browserToken: TOKEN,
        stdin: '\x03',
      });
    }),
  );

  uxIt('no --server: select Cloud EU → browser OAuth', () =>
    withHarness(async (h) => {
      const server = await h
        .newFakeServer()
        .withAuthToken(TOKEN)
        .withOrganizations([{ key: ORG, name: 'My Org' }])
        .start();
      const cloudUrl = server.baseUrl();
      return h.run('auth login', {
        extraEnv: cloudEnvFor(cloudUrl),
        browserToken: TOKEN,
        stdinChunks: ['\r', '\r'], // Enter (Cloud), Enter (EU)
      });
    }),
  );
});
