name: Cleanup PR Resources
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: sonar-xs
    name: Cleanup
    permissions:
      actions: write
    steps:
      - uses: SonarSource/ci-github-actions/pr_cleanup@23d3a5700259f9890438851083904c6d5e87ff4e # 1.3.34
